# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier to identify orders.', primary_key=True, serialize=False)),
                ('Order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('Row_id', models.UUIDField(default=uuid.uuid4, help_text='Unique key to identify an order details.', primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(help_text='Enter the required quantity.')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Code', models.IntegerField(help_text='Enter the code for the product.', primary_key=True, serialize=False)),
                ('Product_name', models.CharField(help_text='Enter the product name.', max_length=250)),
                ('Company', models.CharField(help_text='Enter the company name.', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available_units', models.IntegerField(help_text='Enter the number of available units.')),
                ('Code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique identification for user.', primary_key=True, serialize=False)),
                ('Name_of_the_firm', models.CharField(help_text='Enter the name of your firm.', max_length=100)),
                ('Address', models.TextField(help_text='Enter the Delivery address.', max_length=500)),
                ('Pincode', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_person', models.CharField(help_text='Enter the Name of the contact person.', max_length=50)),
                ('Designation', models.CharField(help_text='Enter the designation of the contact person.', max_length=50)),
                ('Office_phone', models.CharField(help_text='Enter office phone number.', max_length=15)),
                ('Mobile_phone', models.CharField(help_text='Enter mobile number.', max_length=13)),
                ('Drug_License', models.CharField(help_text='Enter the Valid Drug License Number.', max_length=100)),
                ('DL_expiry_date', models.DateField(help_text='Enter the Drug license Expiry date.')),
                ('GSTIN', models.CharField(help_text='Enter the GSTIN number.', max_length=50)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='OrderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='Placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.User'),
        ),
    ]
