# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
